# ################################
# Model: Parkinson's identification with ECAPA
# Author: Briac Cordelle & Peter Plantinga
# ################################

# Basic parameters
seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]
lr_factor: 1

# Save folders and paths
experiment_name: whisper_mlp_pitt_qpn
storage_folder: !PLACEHOLDER # where you want to save results ($HOME/scratch/results on compute canada, maybe just results/ on personal machine)
output_folder: !ref <storage_folder>/<experiment_name>/seed_<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
predictions_file: !ref <output_folder>/predictions.csv
encoded_labels: !ref <save_folder>/label_encoder.txt

# Data files
pd_data_folder: !PLACEHOLDER
ad_data_folder: !PLACEHOLDER
noise_folder: !ref <storage_folder>/noise
pd_train_annotation: !ref <save_folder>/pd_train.json
pd_valid_annotation: !ref <save_folder>/pd_valid.json
pd_test_annotation: !ref <save_folder>/pd_test.json
ad_train_annotation: !ref <save_folder>/ad_train.json
ad_valid_annotation: !ref <save_folder>/ad_valid.json
ad_test_annotation: !ref <save_folder>/ad_test.json
noise_annotation: !ref <save_folder>/noise.csv
ad_valid_metrics_json: !ref <output_folder>/ad_valid_metrics.json
pd_test_metrics_json: !ref <output_folder>/pd_test_metrics.json
ad_test_metrics_json: !ref <output_folder>/ad_test_metrics.json

skip_prep: False
ckpt_interval_minutes: 15 # save checkpoint every N min

# Data for augmentation
NOISE_DATASET_URL: https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1

# Training parameters
epochs: 20
warmup_epochs: 2
samples_per_epoch: 1024
total_batch_size: 32
batch_size: 4
grad_accumulation_factor: !ref <total_batch_size> // <batch_size>
lr: 0.0000217087706389717
base_lr: 0.000000490308763517136
max_lr: !ref <lr>
step_size: 50
sample_rate: 16000
chunk_size: 56.0 # seconds
loss: bce

# Test parameters
test_batch_size: 1
metric_categories: [sex, lang]
threshold: 0.5

# Model parameters
# For the pretrained_source, use the path to the model dir
pretrained_source: !PLACEHOLDER
freeze_pretrained: True
feature_size: 768
embedding_size: 512
dropout: 0.147014385872339
out_neurons: 1

# Dataloader options
# Shuffling handled by sampler in train.py
num_workers: 4
train_dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

valid_dataloader_options:
    batch_size: !ref <test_batch_size>
    num_workers: !ref <num_workers>

test_dataloader_options:
    batch_size: !ref <test_batch_size>
    num_workers: !ref <num_workers>

# AUGMENTATIONS
# Download and prepare the dataset of noisy sequences for augmentation
prepare_noise_data: !name:speechbrain.augment.preparation.prepare_dataset_from_URL
    URL: !ref <NOISE_DATASET_URL>
    dest_folder: !ref <noise_folder>
    ext: wav
    csv_file: !ref <noise_annotation>
    max_length: !ref <chunk_size>

# Add noise to input signal
add_noise: !new:speechbrain.augment.time_domain.AddNoise
    csv_file: !ref <noise_annotation>
    snr_low: 0
    snr_high: 15
    noise_sample_rate: !ref <sample_rate>
    clean_sample_rate: !ref <sample_rate>
    num_workers: !ref <num_workers>

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq: !new:speechbrain.augment.time_domain.DropFreq
    drop_freq_low: 0
    drop_freq_high: 1
    drop_freq_count_low: 1
    drop_freq_count_high: 3
    drop_freq_width: 0.05

# Time drop: randomly drops a number of temporal chunks.
#drop_chunk: !new:speechbrain.augment.time_domain.DropChunk
#    drop_length_low: 1000
#    drop_length_high: 2000
#    drop_count_low: 1
#    drop_count_high: 5

# Augmenter: Combines previously defined augmentations to perform data augmentation
wav_augment: !new:speechbrain.augment.augmenter.Augmenter
    parallel_augment: False
    concat_original: False
    min_augmentations: 2
    max_augmentations: 2
    augment_prob: 0.9
    augmentations: [!ref <add_noise>, !ref <drop_freq>]

# Models
#compute_features: !new:speechbrain.lobes.models.huggingface_transformers.wavlm.WavLM
#    source: !ref <pretrained_source>
#    output_norm: True
#    freeze_feature_extractor: True
#    freeze: !ref <freeze_pretrained>
#    save_path: !ref <output_folder>/wavlm-large

compute_features: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
    source: !ref <pretrained_source>
    encoder_only: True
    freeze: !ref <freeze_pretrained>
    save_path: !ref <output_folder>/whisper

#compute_features: !new:speechbrain.lobes.models.huggingface_transformers.hubert.HuBERT
#    source: !ref <pretrained_source>
#    freeze: !ref <freeze_pretrained>
#    save_path: !ref <output_folder>/whisper

#compute_features: !new:nemo_encoder.NeMoEncoder
#    source: !ref <pretrained_source> / canary-1b.nemo
#    freeze: !ref <freeze_pretrained>
#    nemo_type: "MultiTask"
#    source_dir: !ref <pretrained_source>

#compute_features: !new:xeus_encoder.XEUS_Encoder
#    source: !ref <pretrained_source>
#    freeze: !ref <freeze_pretrained>
#    save_path: !ref <output_folder>/xeus

#compute_features: !new:owsm_encoder.OWSM_Encoder
#    source: !ref <pretrained_source>
#    freeze: !ref <freeze_pretrained>

embedding_model: !new:torch.nn.Sequential
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <feature_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU
    - !new:speechbrain.nnet.pooling.AttentionPooling
        input_dim: !ref <embedding_size>
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <embedding_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: !ref <embedding_size>
    out_neurons: !ref <out_neurons>

# Functions
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <epochs>

modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>

softmax: !new:speechbrain.nnet.activations.Softmax
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

kld_loss: !name:speechbrain.nnet.losses.kldiv_loss
    reduction: sum

aam_loss: !new:speechbrain.nnet.losses.AdditiveAngularMargin
    margin: 0.2
    scale: 30

bce_loss: !name:speechbrain.nnet.losses.bce_loss
    allowed_len_diff: 0
    label_smoothing: 0.01

opt_class: !name:bitsandbytes.optim.Adam8bit
    lr: !ref <lr>
    weight_decay: 0.0001

lr_scheduler: !name:transformers.get_cosine_schedule_with_warmup
    num_warmup_steps: !ref <warmup_epochs> * <samples_per_epoch> // <total_batch_size>
    num_training_steps: !ref <epochs> * <samples_per_epoch> // <total_batch_size>

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Error computation
error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats
    positive_label: 1
error_metric: chunk_F-score

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        counter: !ref <epoch_counter>
