# ################################
# Model: Parkinson's identification with ECAPA
# Author: Briac Cordelle & Peter Plantinga
# ################################

# Basic parameters
seed: 2086
__set_seed: !apply:torch.manual_seed [!ref <seed>]
lr_factor: 1

# Save folders and paths
experiment_name: whisper_small
storage_folder: results
output_folder: !ref <storage_folder>/<experiment_name>/seed_<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
predictions_file: !ref <output_folder>/predictions.csv
encoded_labels: !ref <save_folder>/label_encoder.txt

# Data files
data_folder: !PLACEHOLDER
noise_folder: !ref <data_folder>/noise
rir_folder: !ref <data_folder>/rir
train_annotation: !ref <storage_folder>/train.json
valid_annotation: !ref <storage_folder>/valid.json
test_annotation: !ref <storage_folder>/test.json
#test_annotation: !ref <storage_folder>/human_samples.json
noise_annotation: !ref <save_folder>/noise.csv
rir_annotation: !ref <save_folder>/rir.csv
valid_metrics_json: !ref <output_folder>/valid_metrics.json
test_metrics_json: !ref <output_folder>/test_metrics.json
test_metrics_csv: !ref <output_folder>/test_metrics.csv

skip_prep: False
ckpt_interval_minutes: 15 # save checkpoint every N min

# Data for augmentation
NOISE_DATASET_URL: https://www.dropbox.com/scl/fi/a09pj97s5ifan81dqhi4n/noises.zip?rlkey=j8b0n9kdjdr32o1f06t0cw5b7&dl=1
RIR_DATASET_URL: https://www.dropbox.com/scl/fi/linhy77c36mu10965a836/RIRs.zip?rlkey=pg9cu8vrpn2u173vhiqyu743u&dl=1

# Training parameters
epochs: 20
warmup_epochs: 2
samples_per_epoch: 1024
total_batch_size: 32
batch_size: 8
grad_accumulation_factor: !ref <total_batch_size> // <batch_size>
lr: 0.00015
sample_rate: 16000
chunk_size: 30.0 # seconds
loss: bce

test_keep_keys:
    task: [repeat, read, recall, dpt]

# Test parameters
test_batch_size: 2
metric_categories: [sex, task, severity]
threshold: 0.5

# Model parameters
# For the pretrained_source, use the path to the model dir
pretrained_source: !PLACEHOLDER
freeze_pretrained: True
feature_size: 768
embedding_size: 768
dropout: 0.2
out_neurons: 1

# Dataloader options
test_dataloader_options:
    batch_size: 1

# Models
compute_features: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
    source: !ref <pretrained_source>
    encoder_only: True
    freeze: !ref <freeze_pretrained>
    save_path: !ref <output_folder>/whisper

embedding_model: !new:torch.nn.Sequential
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <feature_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU
    - !new:speechbrain.nnet.pooling.AttentionPooling
        input_dim: !ref <embedding_size>
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <embedding_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: !ref <embedding_size>
    out_neurons: !ref <out_neurons>

# Functions
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <epochs>

modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>

softmax: !new:speechbrain.nnet.activations.Softmax
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

bce_loss: !name:speechbrain.nnet.losses.bce_loss
    allowed_len_diff: 0
    label_smoothing: 0.01

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0.01

lr_scheduler: !name:transformers.get_cosine_schedule_with_warmup
    num_warmup_steps: !ref <warmup_epochs> * <samples_per_epoch> // <total_batch_size>
    num_training_steps: !ref <epochs> * <samples_per_epoch> // <total_batch_size>

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Error computation
error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats
    positive_label: 1
error_metric: chunk_F-score
