
# ################################
# Model: WavLM + ECAPA_TDNN
# Author: Peter Plantinga, Briac Cordelle, others
# ################################

# Basic parameters
lr_factor: 1
seed: !ref 2025 + <lr_factor>
lr: 0.0001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
experiment_name: bert
results_dir: results
output_folder: !ref <results_dir>/<experiment_name>/seed_<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
valid_results_json: !ref <output_folder>/valid_results.json
test_results_json: !ref <output_folder>/test_results.json

# Data files
data_folder: !PLACEHOLDER
transcript_folder: transcripts/

manifests:
  train: !ref <output_folder>/train.json
  valid: !ref <output_folder>/valid.json
  test: !ref <output_folder>/test.json
valid_predictions_file: !ref <output_folder>/valid_predictions.csv
test_predictions_file: !ref <output_folder>/test_predictions.csv
prep_ssl: False

skip_prep: False
ckpt_interval_minutes: 15 # save checkpoint every N min

# Training parameters
epochs: 30
samples_per_epoch: 256 # roughly size of dpt
batch_size: 16
grad_accumulation_factor: 4
base_lr: !ref <lr> / 1000
max_lr: !ref <lr>
label_smoothing: 0.01
step_size: 2000
chunk_size: 15
#remove_keys: {"sex": "M"}
remove_keys: {"task": ["hbd", "repeat", "vowel_repeat", "recall", "read_text"]}

# Feature parameters
name_of_layers_module: encoder.layer
llrd_alpha: 0.9 # layer-wise learning rate decay

# Model parameters
embedding_size: 1024

# Number of classes
weight_hc: 1.
weight_pd: 1.
out_neurons: 2

# Test parameters
max_test_chunks: 24
test_batch_size: 2
result_categories: ["sex", "task"]
threshold: 0.5

# Dataloader options
num_workers: 6
train_dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

valid_dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

test_dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

# Functions
tokenizer: !apply:transformers.BertTokenizer.from_pretrained
    - bert-base-multilingual-cased

compute_features: !apply:transformers.BertModel.from_pretrained
    pretrained_model_name_or_path: bert-base-multilingual-cased
    output_hidden_states: True

projection_size: 768
embedding_model: !new:torch.nn.Sequential
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <projection_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU
    - !new:speechbrain.nnet.pooling.AttentionPooling
        input_dim: !ref <embedding_size>
    - !new:speechbrain.nnet.linear.Linear
        input_size: !ref <embedding_size>
        n_neurons: !ref <embedding_size>
    - !new:torch.nn.Dropout
        p: !ref <dropout>
    - !new:torch.nn.LeakyReLU

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: !ref <embedding_size>
    out_neurons: !ref <out_neurons>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <epochs>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

softmax: !new:speechbrain.nnet.activations.Softmax
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:torch.nn.functional.cross_entropy

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

scheduler: !name:transformers.get_cosine_schedule_with_warmup
    num_warmup_steps: 200
    num_training_steps: 4000

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
    base_lr: !ref <base_lr>
    max_lr: !ref <max_lr>
    step_size: !ref <step_size>

# Error computation
error_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats
    positive_label: 1
error_metric: F-score

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

class_stats: !name:speechbrain.utils.metric_stats.ClassificationStats

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        #compute_features: !ref <compute_features>
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>
        lr_annealing: !ref <lr_annealing>
