
# ################################
# Model: WavLM + ECAPA_TDNN
# Author: Peter Plantinga, Briac Cordelle, others
# ################################

# Basic parameters
lr_factor: 1
seed: !ref 2025 + <lr_factor>
lr: 0.001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
experiment_name: wavrx
results_dir: results
output_folder: !ref <results_dir>/<experiment_name>/seed_<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER
manifests:
  train: !ref <output_folder>/train.json
  valid: !ref <output_folder>/valid.json
  test: !ref <output_folder>/test.json
test_predictions_file: !ref <output_folder>/test_predictions.csv
ssl_weights_file: !ref <output_folder>/ssl_weights.txt
prep_ssl: False

skip_prep: False
ckpt_interval_minutes: 15 # save checkpoint every N min

# Training parameters
epochs: 30
batch_size: 2
grad_accumulation_factor: 8
test_batch_size: 1
base_lr: !ref <lr> / 1000
max_lr: !ref <lr>
step_size: 2000
sample_rate: 16000
sentence_len: 15.0 # seconds
shuffle: True
weights: [0.15, 0.55, 0.3] # roughly 900 negs, 200 mild, 500 severe
label_smoothing: 0.01

# Feature parameters
wavlm_hub: ../../ssl-models/wavlm-large
wavlm_folder: !ref <output_folder>/wavlm-large
freeze_wavlm_extractor: True
freeze_wavlm: True
lr_wavlm: 0.0001
name_of_layers_module: feature_extractor.encoder.layers
llrd_alpha: 0.9

# Number of classes
out_neurons: 3

# Dataloader options
num_workers: 4
dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: !ref <shuffle>
    num_workers: !ref <num_workers>

test_dataloader_options:
    batch_size: !ref <test_batch_size>
    shuffle: !ref <shuffle>
    num_workers: !ref <num_workers>

# Augmentations would be here
# See voxceleb recipe to add them back
# For now we are going without and we will add them (one at a time) once we are
# sure of our preliminary results

# Functions
projection_size: 768
compute_features: !new:wavrx.WavRx
    #ssl_encoder_source: !ref <wavlm_hub>

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <projection_size>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    groups: [1, 1, 1, 1, 1]
    attention_channels: 128
    lin_neurons: 192

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: 192
    out_neurons: !ref <out_neurons>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <epochs>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

softmax: !new:speechbrain.nnet.activations.Softmax
log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss
    allowed_len_diff: 0

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wavlm_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_wavlm>

scheduler: !name:transformers.get_cosine_schedule_with_warmup
    num_warmup_steps: 200
    num_training_steps: 2000

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
    base_lr: !ref <base_lr>
    max_lr: !ref <max_lr>
    step_size: !ref <step_size>

lr_annealing_wavlm: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_wavlm>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

class_stats: !name:speechbrain.utils.metric_stats.ClassificationStats

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        #compute_features: !ref <compute_features>
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>
        lr_annealing: !ref <lr_annealing>
